name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matplotlib-example:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # TODO improve dependency management (cache!)
      - name: set up dependencies
        run: |
          pip3 install --user numpy scipy matplotlib

      # Runs a set of commands using the runners shell
      - name: Create matplotlib example plots
        run: |
          cd $GITHUB_WORKSPACE/examples/matplotlib
          python3 example.py
      
      - name: upload plot
        uses: actions/upload-artifact@v3
        with:
          name: matplotlib-example
          path: $GITHUB_WORKSPACE/examples/matplotlib/example.matplotlib.png
  #root-example:
  #  runs-on: rootproject/root
  #  steps:
  #    - uses: uses: actions/checkout@v3
     
