name: Matplotlib CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
   branches: [ "main" ]
   paths: ['src/matplotlib/**', 'examples/matplotlib/**']
  pull_request:
   branches: [ "main" ]
   paths: ['src/matplotlib/**', 'examples/matplotlib/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matplotlib-example:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: set up dependencies
        run: |
          pip install numpy scipy matplotlib
          pip install $GITHUB_WORKSPACE

      - name: Create matplotlib example plots
        run: |
          cd $GITHUB_WORKSPACE/examples/matplotlib
          python3 example.py

      - name: upload plot
        uses: actions/upload-artifact@v3
        with:
          name: matplotlib-example
          path: ${{ github.workspace }}/examples/matplotlib/example.matplotlib.pdf
          if-no-files-found: error
